In [3]:
# Matrix in numpy 
import numpy as np
# matrix declaration 
arr = np.matrix([[1,2],[3,4]])
arr2 = np.matrix([[1,2],[3,4]])
print(arr)
# matrix addititon 
print(arr+arr2)
print(arr-arr2)
print(arr*arr2)
print(arr.dot(arr2))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [9]:
# Matrix function 

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
# Transpose -> transpose(array)
print(np.transpose(var))
print(var.T)

var2 = np.matrix([[1,2],[3,4]])
print(var2)
# Swapaxes -> swapaxes(array,axis-1, axis-2)
print(np.swapaxes(var2,1,0))

# Inverse 
print(np.linalg.inv(var2))

# Power -> matrix_power(array, power)
print(np.linalg.matrix_power(var2, 2))

# Determinant -> 
print(np.linalg.det(var2))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 7 10]
 [15 22]]
-2.0000000000000004
