In [3]:
# Copy vs view 
import numpy as np
arr = np.array([1,2,3,4,5])
coarr = arr.copy()
viarr = arr.view()
arr[3]= 40
print("Array= ", arr)
print("Copied Array= ", coarr)
print("Viewed Array= ", viarr)

Array=  [ 1  2  3 40  5]
Copied Array=  [1 2 3 4 5]
Viewed Array=  [ 1  2  3 40  5]


In [8]:
# Joining arrays in numpy 
# 1-D Array 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7])
narr = np.concatenate((arr1,arr2))
# print(narr)
# 2-D Array 
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
narr1 = np.concatenate((arr1,arr2))  #Default axis = 0
narr2 = np.concatenate((arr1,arr2), axis = 1)
# print(narr1)
# print(narr2)

# Joining using stack()
var1 = np.array([1,2,3,4,5])
var2= np.array([6,7,8,9,10])
a_new = np.stack((var1,var2),axis = 0)
a_new0 = np.stack((var1,var2),axis = 1)
a_new1 = np.hstack((var1,var2))  #row
a_new2 = np.vstack((var1,var2))  #column
a_new3 = np.dstack((var1,var2))  #height
print(a_new)
print(a_new0)
print(a_new1)
print(a_new2)
print(a_new3)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [17]:
# Splitng of array 
ar = np.array([1,2,3,4,5,6])
var = np.array_split(ar, 3)
print(var)
print(var[0])

ar1 = np.array([[1,2,3],[4,5,6]])
varr1 = np.array_split(ar1, 3)
varr2 = np.array_split(ar1, 3,axis = 1)
print(varr1)
print(varr2)


[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
