In [4]:
# Searching in array (REturn index2)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr == 2)
y = np.where((arr%2)==0)
print(x)
print(y)

# Searching in sorted array 
arr1 = np.array([2,4,6,8,10,12])
x1 = np.searchsorted(arr1,5)
x2 = np.searchsorted(arr1,5, side = 'right')  # It will search for index from right side
x3 = np.searchsorted(arr1,[5,7,9], side = 'left')
print(x1)   # Retutns the index where 5 is placed so that array will be sorted
print(x2)
print(x3)

(array([1], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)
2
2
[2 3 4]


In [5]:
# Sorting a array 
var = np.array([4,6,2,3,1,5,9,7,8])
print(np.sort(var))

var1= np.array(['f', 'a', 'd', 'r'])
print(np.sort(var1))

var2 = np.array([[5,1,3],[9,6,3],[2,6,8]])
print(np.sort(var2))

[1 2 3 4 5 6 7 8 9]
['a' 'd' 'f' 'r']
[[1 3 5]
 [3 6 9]
 [2 6 8]]


In [6]:
# Filter array 
ar= np.array([2,4,6,8])
f = [True, False, False, True]
new = ar[f]
print(new)

[2 8]


In [5]:
# Shuffle the array 
import numpy as np
yar = np.array([1,2,3,4,5])
np.random.shuffle(yar)
print(yar)

yar1 = np.array([1,2,3,2,3,4,2,1,3,4])
new1 = np.unique(yar1)  # Returns element for once
new2 = np.unique(yar1, return_index= True, return_counts= True)  # returns the element and its index, no. of occurance
print(new1)
print(new2)

# Resize an array 
yar2 = np.array([1,2,3,4,5,6])
new3 = np.resize(yar2, (2,3))
print(new3)
print(new3.flatten())  # Converting a 2-D array to 1-D array
print(new3.flatten(order= 'F'))  # Flatten in column-major order
print(new3.flatten(order= 'C'))  # Default- Flatten in row-major order
print(np.ravel(new3))

[3 5 4 2 1]
[1 2 3 4]
(array([1, 2, 3, 4]), array([0, 1, 2, 5], dtype=int64), array([2, 3, 3, 2], dtype=int64))
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
