In [31]:
# Insertion
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
v1 = np.insert(arr,2,34)
v2 = np.insert(arr,(2,4),34)
v3 = np.insert(arr,(2,4),3.4)
print(v1)
print(v2)
print(v3)
#In 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
y1= np.insert(arr2, 2, 6)
print(y1)

# Append
v4 = np.append(arr,7.5)
print(v4)
#In 2-D array
y2 = np.append(arr2,[[2,3,40]], axis=0)
print(y2)
# print(y3)

# Delete -> np.delete(array,position)
d = np.delete(arr, 2)
print(d)

[1 2 3 4 5 6]
[ 1  2 34  3  4  5  6]
[ 1  2 34  3  4 34  5  6]
[1 2 3 3 4 3 5 6]
[1 2 6 3 4 5 6]
[1.  2.  3.  4.  5.  6.  7.5]
[[ 1  2  3]
 [ 4  5  6]
 [ 2  3 40]]
[1 2 4 5 6]
