In [4]:
# How to create NumPy Array 
# 1-D Array
import numpy as np
x= np.array([1,2,3,4])
print(x)
print(x.ndim)

[1 2 3 4]
1


In [6]:
# 2-D Array
y= np.array([[1,2,3,4],[1,2,3,4]])
print(y)
print(y.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [7]:
# 3-D Array
z= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(z)
print(z.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
