In [1]:
# Array filled with 0's
import numpy as np
ar_zero = np.zeros(4)  #1-D Array
print(ar_zero)
ar_zero1 = np.zeros((3,4))  #2-D Array
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
# Array filled with 1's
import numpy as np
ar_one = np.ones(4)  #1-D Array
print(ar_one)

[1. 1. 1. 1.]


In [3]:
# Empty Array
import numpy as np
ar_em = np.empty(4)
print(ar_em)  #It will give the previous array

[1. 1. 1. 1.]


In [5]:
# An array with a range of elements
import numpy as np
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [9]:
# Array diagonal element filled with 1's 
import numpy as np
ar_dia = np.eye(3)
print(ar_dia)
print( )
ar_dia1 = np.eye(3,4)
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [10]:
# An array with values that are spaced linearly on a specified interval
import numpy as np
ar_lin = np.linspace(0,10, num = 5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
