In [9]:
# NumPy array with random numbers 
import numpy as np
# rand() -> This function is used to generate a random vlaue between 0 to 1
ar1 = np.random.rand(4)
print(ar1)
# randn() -> This function is used to generate a random vlaue close to 0. This may return positive or negative numbers as well
ar2 = np.random.randn(4)
print(ar2)
# ranf() -> This function is used to generate a random vlaue in the interval [0.0, 1.0)
ar3 = np.random.randn(4)
print(ar3)
# randint() -> This function is used to generate a random vlaue between a given range
randit(min, max, no. of numbers)
ar4 = np.random.randint(3,13,5)
print(ar4)

[0.8869215  0.97684191 0.69657612 0.46184171]
[-0.0494542  -0.06992191 -0.15228731  0.64835636]
[0.59859721 1.48521533 2.18509591 0.80307273]
[ 4 11  7 11  8]
