In [2]:
# Data type of NumPy Array
import numpy as np
arr1 = np.array([1,2,3,4,15])
print("Data type of arr1 is", arr1.dtype)
arr2 = np.array(["A", "G", "T", "F"])
print("Data type of arr2 is", arr2.dtype)
arr3 = np.array(["A", "G", "T", "F", 1,2,3,4,15])
print("Data type of arr3 is", arr3.dtype)

Data type of arr1 is int32
Data type of arr2 is <U1
Data type of arr3 is <U11


In [8]:
# Changing Data types 
# Method 1 
x = np.array([1,2,3,4], dtype = np.int8)
print(x.dtype)
print(x)
# Method 2
y = np.array([1,2,3,4], dtype = "f")
print(y.dtype)
print(y)
# Method 3
z = np.array([1,2,3,4])
new = np.float32(z)
print(z.dtype)
print(new.dtype)
print(z)
print(new)
# Method 4 
new1= z.astype(float)
print(new1)
print(new1.dtype)

int8
[1 2 3 4]
float32
[1. 2. 3. 4.]
int32
float32
[1 2 3 4]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
float64


: 