In [6]:
# Arithmetic Operation
import numpy as np
arr1 = np.array([1, 2, 3, 4])
ans1= arr1 + 3      # We can do -, *, /, %, ** too
print(ans1)
arr2 = np.array([5, 6, 7, 8])
ans2 = arr1 + arr2
print(ans2)
ans3 = np.add(arr1, arr2)
print(ans3)
# Reciprocal 
rec = np.reciprocal(arr1)
print(rec)

[4 5 6 7]
[ 6  8 10 12]
[ 6  8 10 12]
[1 0 0 0]


In [7]:
# Arithmetic Functions
# min(), max(), argmin()
import numpy as np
arr = np.array([3,4,1,5,2,4,5,2])
print("Minimum element in the array is", np.min(arr), "Index is", np.argmin(arr))
print("Maximum element in the array is", np.max(arr), "Index is", np.argmax(arr))

# In 2-D array axis = 0 -> column
#              axis = 1 -> row
arr1 = np.array([[2,1,9], [7,4,2]])
print(np.min(arr1, axis = 1))
print(np.min(arr1, axis = 0))

# sqrt(), sin(), cos(), cumsum()
print("Sqrt = ",np.sqrt(arr))
print("Sin = ",np.sin(arr))
print("Cos = ",np.cos(arr))
print("Cummiltive sum = ",np.cumsum(arr))

Minimum element in the array is 1 Index is 2
Maximum element in the array is 5 Index is 3
[1 2]
[2 1 2]
Sqrt =  [1.73205081 2.         1.         2.23606798 1.41421356 2.
 2.23606798 1.41421356]
Sin =  [ 0.14112001 -0.7568025   0.84147098 -0.95892427  0.90929743 -0.7568025
 -0.95892427  0.90929743]
Cos =  [-0.9899925  -0.65364362  0.54030231  0.28366219 -0.41614684 -0.65364362
  0.28366219 -0.41614684]
Cummiltive sum =  [ 3  7  8 13 15 19 24 26]


: 