In [11]:
# Shape and Reshaping of Array 
import numpy as np
arr = np.array([[1,2,3,4], [1,2,3,4]])
print(arr)
print(arr.shape) # Simply no. of commas + 1
arr1= np.array([1,2,3,4], ndmin=4)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

# Reshaping
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print(var.ndim)
# Reshaping to 2-D Array
x = var.reshape(3,4)  #reshape(no. of rows, no. of columns)
print(x)
print(x.ndim)
# Reshaping to 2-D Array
y = var.reshape(2,3,2) 
print(y)
print(y.ndim)

# Reshaping the 3-D arrar to 1-D array
z= y.reshape(-1)
print(z)
print(z.ndim)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
