In [3]:
# Broadcasting 
# Rules - Array has same dimension or 1 in the shape eg: ((1,3) & (3,1)), (2,3) & (2,1)
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(arr.shape)
arr1 = np.array([[1], [2], [3]])
print(arr1)
print(arr1.shape)
print(arr + arr1)


[1 2 3]
(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
